### ISSUE TITLE
Data Replication

### ISSUE THREAD

**Issue by lisapatel12** [gramps-project/gramps-web#129]
Is data replication compatible with gramp.js? If so, may you please further elaborate on how it can be done or if you have an open source code ready for it?

**Comment by DavidMStraub** [comment]
Can you please elaborate what exactly you mean? There is the XML export feature and the desktop sync feature for instance.

**Comment by lisapatel12** [comment]
For example, if I upload data for one person on Device A, when I open up device B, the data is already loaded and replicated onto any devices that I use if that makes sense. What would be the most efficient way to do that?

**Comment by DavidMStraub** [comment]
Gramps.js is the frontend for [Gramps Web](https://gramps-project.github.io/web/) which is a complete web app with a REST API backend called [Gramps Web API](https://github.com/gramps-project/gramps-webapi/). So accessing it from different devices is definitely one of the main use cases.

**Comment by lisapatel12** [comment]
So if I use Gramps Web API, I would be able to sync and replicate data providing access to different devices? Is there already a source code written for this type of use?

**Comment by DavidMStraub** [comment]
It depends on what you want to achieve.

You can use it only in the browser - in that case, no additional tool is needed.

You can get full backups anytime by downloading an XML export.

If you want to use Gramps desktop on your PC and Gramps Web in your browser, then yes, you have to use the sync addon.
