### ISSUE TITLE
Edit Person -> Manage Names: Cannot remove a surname

### ISSUE THREAD

**Issue by StephenAdams-hamont** [gramps-project/gramps-web#149]
In my imported database many of the women will have 2 names under "married name", usually one given, one taken. I have been editing this to more correctly use the Birth Name/Married name.

Within the web editor there is no ability to remove a surname from the list of surnames available.

![image](https://user-images.githubusercontent.com/33077783/209994558-fc55f187-e0a6-4cc5-9d1e-cacc669842d7.png)

I want to delete this surname, but it's not possible.
![image](https://user-images.githubusercontent.com/33077783/209994611-e2684972-4876-4862-adfa-4077d8bdaf66.png)

**Comment by StephenAdams-hamont** [comment]
Also, pressing escape from this dialog causes the edit button to become unresponsive.

**Comment by BlitzundBogen** [comment]
I would like to try to fix this. It's also annoying for me, that I always have to set the type of name again when I am editing. 😄 Also I want to have the possibility to delete an alternative name.
