### ISSUE TITLE
Media added to person not showing up as thumbnail on browsing/no option to link as "profile picture"

### ISSUE THREAD

**Issue by StephenAdams-hamont** [gramps-project/gramps-web#157]
In the demo version of Gramps.js images are used, at a minimum, on the home page when linked to the Home Person.

I have set up a clean install, imported a tree, identified myself on the tree. I then uploaded a file using Add New Media.

The image appears on the gallery page but has not been applied anywhere else. No obvious control to make this happen.

**Comment by DavidMStraub** [comment]
Hi, do I understand correctly that you imported an existing Gramps XML of a database that alreay contains media files, but are missing the actual media files? In that case, you have to upload the "missing" files to the backend.

There are several options:

- using curl (or something equivalent) and posting the files to [the appropriate endpoint](https://gramps-project.github.io/gramps-webapi/#/media/updateFile)
- uploading the files to the appropriate directory on the server using SFTP (or something equivalent)
- using the [Gramps Web Sync addon](https://gramps-project.github.io/web/user-guide/sync/)

The last option is certainly the most convenient at present.

Please also see step 4 in [this documentation](https://gramps-project.github.io/web/Deployment/).

When you add a new media file via the web UI, you are creating a new Gramps media object. Linking that to existing Gramps objects (like people, events etc.) is achieved by going to edit mode (blue fab button) and clicking the add link button in the gallery tab.

**Comment by StephenAdams-hamont** [comment]
Not quite. I added a new media object through the web interface. This was not previously known or linked to the offline grams database.

**Comment by StephenAdams-hamont** [comment]
It does not.

**Comment by StephenAdams-hamont** [comment]
I think I've figured it out by going back to the gramps desktop version. There are 2 media references on the person that are not uploaded, aka broken links. Odds are that's what's being referenced in gramps web, and so the web interface doesn't think there's a need to associate the "only" image with the profile picture.

So that leaves us with 
- why aren't the "broken" links shown in the media gallery so that we could delete them?
- is there a way to choose between multiple valid media in the gallery to associate with the profile picture?
