### ISSUE TITLE
Translations for reports options are not pulled in

### ISSUE THREAD

**Issue by MedicMomcilo** [gramps-project/gramps-web#194]
It seems that some of the translations for the options in Reports section are not pulled in.

I'll take Fan Chart as an example:
In its options, there are strings displayed in English (e.g. "Background color is either white or generation dependent").
However, some other strings for the same report are translated (shown in green):

---
![image](https://user-images.githubusercontent.com/7031596/229701512-8f18d022-11be-4a3c-8cec-7f86a1ad8171.png)

---

When I tried to translate it in Weblate, I saw that the string is already [translated](https://hosted.weblate.org/translate/gramps-project/gramps/sr/?checksum=f10859ff74c75ec6) (and it's been like that for a year):

---

![image](https://user-images.githubusercontent.com/7031596/229702379-bbf1555d-2962-43bc-b1af-71c0cae46480.png)

---

I've observed the same behavior on other reports as well.
Please let me know if there is anything I can help with or provide more information on this.

Kind regards,
Momo.

**Comment by DavidMStraub** [comment]
As mentioned in #191, the default Docker image is based on Gramps 5.1.5, which has been released 14 months ago. So my guess as that "a year ago" is after that.

**Comment by MedicMomcilo** [comment]
Ah, that makes sense...
Sorry for not connecting the dots 😉

Is there any documentation on how to chain build everything together?

I'm keen to get my relative excited about self-hosted option for genealogy (I was always Gramps user, but he used some proprietary things), and I think the translation would be a huge plus 😄

Otherwise, I guess you can close this issue and let's hope we don't have to wait for too long for the next release. 😉

**Comment by MedicMomcilo** [comment]
@DavidMStraub I see that 5.1.6 was (semi) recently released, but I don't see in the release notes that translations are updated. I've tested with latest Gramps Web and I still see the same issues as described above.

Is my understanding correct that this release didn't pull the translation updates in, or am I doing something wrong?

**Comment by DavidMStraub** [comment]
Hi, you are right, the reason is that no .deb package has been released for 5.1.6. I don't know why; I already asked on the Gramps dev mailing list and haven't received a reply yet.

**Comment by Nick-Hall** [comment]
There were no translation updates with v5.1.6 release.  Weblate is only used for the _master_ branch.

**Comment by MedicMomcilo** [comment]
Hello!

I'm sorry, I don't understand what this implies.
We won't see updated translations until v5.2.*, or something like that?

If so, how about those inconvenient instructions for manually adding them? :slightly_smiling_face:

**Comment by Nick-Hall** [comment]
There will be no further releases in the _gramps51_ branch.

Instructions for [translating](https://gramps-project.org/wiki/index.php/Translating_Gramps#Testing_your_.po_file) Gramps manually can be found in the wiki.

There are 3 basic steps:
1. Update the `po` file.
2. Compile it with `msgfmt`.
3. Replace your existing `mo` file.

**Comment by Nick-Hall** [comment]
Any changes made to the "v5.2" component in Weblate will create a pull requests in the _gramps52_ maintenance branch.  These will be merged before the next release.

Changes made to the "Development" component will get merged in the _master_ branch at some point.

**Comment by MedicMomcilo** [comment]
@Nick-Hall Thanks for clarifying, it makes perfect sense now :+1: 

@DavidMStraub I guess we wait for v5.2.0 and docker rebase to it, then my translations will be visible in Gramps Web as well :wink: 

Thank you both, your help and explanations are very welcome and appreciated! :heart: 
I'll close this issue as soon as I can confirm that my expectations are correct.

**Comment by MedicMomcilo** [comment]
@DavidMStraub indeed it is!

Thanks for all the hard work :+1: 

Closing the issue.
