### ISSUE TITLE
Repo name change?

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-web#334]
I was wondering whether changing the repository name to something like `gramps-web-frontend` could reduce users' confusion. Any opinions (on changing the name, and what to change it to)?

**Comment by zeitchef** [comment]
I see there is also `gramps-webapi` so either `gramps-web` or move both to `grampsweb-api` and `grampsweb-frontend`?

**Comment by DavidMStraub** [comment]
My suggestion is:

- `gramps-project/Gramps.js` &rarr; `gramps-project/grampsweb-frontend`
- `gramps-project/gramps-webapi` &rarr; `gramps-project/grampsweb-api`
- `gramps-project/web` &rarr; `gramps-project/grampsweb-docs`

The last one was only named `web` to have a shorter URL `gramps-project.github.io/web`, but now we have `grampsweb.org` anyway. Other options for that one would be `grampsweb-website`, `grampsweb-documentation`, or `grampsweb-org`.

**Comment by DavidMStraub** [comment]
The discussion at https://github.com/gramps-project/gramps-webapi/issues/473 leaves the following options:

- `gramps-project/gramps-web`
- `gramps-project/gramps-web-frontend`

I think the former is clearer for users, the latter clearer for developers. So still unsure. :game_die: :game_die:

**Comment by DavidMStraub** [comment]
I plan to rename to `gramps-project/gramps-web` tomorrow, last chance to weigh in.
