### ISSUE TITLE
Tracking changes (by user)

### ISSUE THREAD

**Issue by james-cook** [gramps-project/gramps-web#350]
I have been following this project for some time.
And did try the test site some time ago.

I'm finally hoping to set this up locally to test (docker) and then on the web.
My hope is that family members will help research our history together.

My question is that for a particular entry are the changes made logged in any way?
Can they be viewed and are individual changes assigned to the users that made them?
Gramps desktop is great but I always wish it had a way of tracking (nachvollziehen!) the changes I make myself (let alone others!).

Sorry if I missed any documentation on this - any pointers very welcome

**Comment by DavidMStraub** [comment]
We have Gramps 5.2 now, so one step closer to unblocking this :crossed_fingers:

**Comment by DavidMStraub** [comment]
Implemented in #417 :tada:
