### ISSUE TITLE
Request instructions for gathering Version information for issue reports

### ISSUE THREAD

**Issue by emyoulation** [gramps-project/gramps-web#359]
In the GrampsWeb user documentation, there is nothing about gathering version information needed for troubleshooting.  

With Gramps desktop, users are instructed to use the "About Gramps" dialog to gather information about the configuration.  (There are "Select All" and "Copy" context menus in that dialog. But they are not obvious and users rarely notice these features.)
![image](https://github.com/gramps-project/gramps-web/assets/69127217/cca87a9e-4205-41dd-a8e0-e514b269f6b3)

Please add something similar. And/or describe the process to gather the information to https://www.grampsweb.org/help/

![image](https://github.com/gramps-project/gramps-web/assets/69127217/bde4633c-d419-4c9d-a595-2ce725340c70)

**Comment by emyoulation** [comment]
Also the text needs disambiguation:

Where it says "There are two separate repositories" in "Reporting Issues", revise to "There are two separate **GitHub** repositories"

And in "Suggesting enhancements", where it says "a feature request on GitHub", revise to   "a feature request **in the appropriate frontend or backend** GitHub **repository.**"

**Comment by DavidMStraub** [comment]
Good suggestions! By the way, you are also welcome to contribute directly to https://github.com/gramps-project/gramps-web-docs if you feel like it :slightly_smiling_face:

**Comment by emyoulation** [comment]
Typo:
'version' missing a letter: 
"hosted vesion such as Grampshub"

https://www.grampsweb.org/help/

I cannot diectly edit your documentation on Grampsweb.com 
Or can I?

Note that this section is in the 'Administrator' section of the docs. Is the Settings page info accessible to visitors of a Gramps Web site too? 

I assume that there will be future occurrences of visitors wanting to report a problem submitting a problem when trying to collaborate with GrampsWeb. And you would want something in that information to clearly indicate that the question is not coming from an administrator of a Gramps Web instance but from a Registered visitor to a specific Tree.

**Comment by emyoulation** [comment]
Typo:
'version' missing a letter: 
"hosted vesion such as Grampshub"

https://www.grampsweb.org/help/

I cannot diectly edit your documentation on Grampsweb.com 
Or can I?

Note that this section is in the 'Administrator' section of the docs. Is the Settings page info accessible to visitors of a Gramps Web site too? 

I assume that there will be future occurrences of visitors wanting to report a problem submitting a problem when trying to collaborate with GrampsWeb. And you would want something in that information to clearly indicate that the question is not coming from an administrator of a Gramps Web instance but from a Registered visitor to a specific Tree.



In re-reading the Discourse forum thread, I am unable to conclude if the question is from an Admin of a Gramps Web instance or someone logged in as a registered Visitor. Perhaps Admins should have a different color titlebar?
![76b9b9a0e08d9fe0bbf6d7afff929d261cce6574.png](https://github.com/gramps-project/gramps-web/assets/69127217/5e9227d2-2a95-4798-9504-984f441c9df8)

**Comment by DavidMStraub** [comment]
> I cannot diectly edit your documentation on Grampsweb.com
> Or can I?

You can! Just clone https://github.com/gramps-project/gramps-web-docs and submit a pull request. The site is served via Github pages.

Another thing that needs to be documented better!

> Note that this section is in the 'Administrator' section of the docs. Is the Settings page info accessible to visitors of a Gramps Web site too?

Yes, the version info screen should be accessible by all users.

**Comment by emyoulation** [comment]
Can you recommend a desktop WYSIWYG markdown editor for people who want to contribute?  I was looking at [Awesome Markdown Editors & (Pre)viewers](https://github.com/mundimark/awesome-markdown-editors) on GitHub...
and Holocron looked interesting. (Since Holocron claims to support GitHub PR generation.)

Opening README.md files in Firefox on Fedora is a terminal mistake. Firefox goes into an endless loop of opening another tab for that markdown file, which opens another tab for that file, which opens...
