### ISSUE TITLE
Color code for gender

### ISSUE THREAD

**Issue by lucaberti** [gramps-project/gramps-web#372]
There seems to be some problem with the gender color coding. Moreover, it seems to depend on the tree context (who is the person "in focus"). These are some examples: 

![gramps prob 3](https://github.com/gramps-project/gramps-web/assets/18533461/d0f1c735-1821-47c3-9b9e-d9360c2741b1)
![gramps prob 1](https://github.com/gramps-project/gramps-web/assets/18533461/14fc9630-900b-43b2-8195-71233410dc6e)
![gramps prob 2](https://github.com/gramps-project/gramps-web/assets/18533461/4937d9fb-8aef-4be4-9ce7-fd45b3024b9e)

Gramps 5.1.6
Gramps Web API 1.5.0
Gramps.js 24.1.0
locale: en
multi-tree: false
task queue: true

**Comment by DavidMStraub** [comment]
Good catch! I can confirm that with my own tree.

**Comment by DavidMStraub** [comment]
It looks like descendants are always blue, while for ancestors it is correct.

**Comment by lucaberti** [comment]
> It looks like descendants are always blue, while for ancestors it is correct.

Sometimes they seem inverted. I.e. this one:

![gramps prob 1](https://github.com/gramps-project/gramps-web/assets/18533461/d9897f25-5845-41d9-9551-ff8c534a3690)

Not sure why, since in other instances, colors of ancestors are correct. I'm looking into it.

**Comment by lucaberti** [comment]
It looks like to me that selected person is also always blue.

**Comment by DavidMStraub** [comment]
>  Don't know if this is relevant, but blue is the only color also in the person detail:

That's different - this is not the "boyish" light blue, but the dark blue that indicates any editable element. This only shows up in edit mode as well, as we don't show a gender icon outside edit mode.

**Comment by lucaberti** [comment]
> That's different - this is not the "boyish" light blue, but the dark blue that indicates any editable element. This only shows up in edit mode as well, as we don't show a gender icon outside edit mode.

Fair enough. Still quite confusing IMHO
