### ISSUE TITLE
Add tree ID, username and permissions level to System Information

### ISSUE THREAD

**Issue by emyoulation** [gramps-project/gramps-web#376]
Some complaints will be because the Permission Level doesn't enable the feature a user reads about. (And sometimes the "Owner" will forget which tabs are accessible at lower levels.) The User won't be able to tell us about their Permission Level because only users at Owner level have access to the "Manage User" preferences tab can see the Permissions Level of any particular account.  

We could spend a lot of energy on Discourse troubleshooting a simple Permissions issue for no reason. 

* The Username and permissions level should show beside the "LOGOUT" button in User Settings 
* The tree ID, username and permissions level should be included in the System Information that can be "Copy to clipboard"

**Comment by DavidMStraub** [comment]
Agreed, except tree ID & username should not be in the copied data as they can represent personally identifiable information.
