### ISSUE TITLE
Demo is not resetting Users and is refusing to commit changes

### ISSUE THREAD

**Issue by emyoulation** [gramps-project/gramps-web#378]
What is the schedule for resetting the  https://demo.grampsweb.org ? It doesn't seem to have reset in over a week.

And is just the Tree data reset? Or also the User list?  (The User list exposes eMail addresses of added Users when experimenting with the "Owner" login. So it needs regular flushing to minimize exposure.)

Any attempt to make changes to the Tree or Users is giving a "500" server error. (Tried to Add a person and to change the a user from "unconfirmed" to "member"

**Comment by DavidMStraub** [comment]
The demo is reset every two hours. I cannot confirm that objects stay there for days - when I checked it just now, it was completely lacking any non-standard objects or users.

I can however confirm that users cannot be edited. Looking into it.

**Comment by DavidMStraub** [comment]
Fixed by https://github.com/DavidMStraub/gramps-web-demo-script/commit/d64c8cb8e789fc5db894697908471c8f8da2dbdd.
