### ISSUE TITLE
Requesting a "Lost Password" reminder has misleading error message when no eMail address is known

### ISSUE THREAD

**Issue by emyoulation** [gramps-project/gramps-web#379]
For the https://demo.grampsweb.org, the Owner, Editor, Contributor, and Member accounts have no eMail account. (Which the GUI doesn't permit. So they must have been created from the user import.) 

When using the "Lost password?" screen the "RESET PASSWORD" responds "Error: User not found." for those accounts.  But the User WAS found, just didn't have a valid eMail value.

**Comment by DavidMStraub** [comment]
Confirmed.
