### ISSUE TITLE
Dev Setup: Api-Container issue with example gramps file

### ISSUE THREAD

**Issue by BlitzundBogen** [gramps-project/gramps-web#403]
File could not be found:
https://github.com/gramps-project/gramps-web/blob/6bc33226fa78bd959e865aa7cb67c135b85a878a/dev/Dockerfile.api#L8

I could start the container by copying a local gramps file instead (as a workaround).

**Comment by DavidMStraub** [comment]
Good catch. The path changed due to the switch to pip install for Gramps 5.2. Please try now.

**Comment by BlitzundBogen** [comment]
Thanks for fixing! Works 🚀
