### ISSUE TITLE
Weblate not pushing?

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-web#406]
For some reason, Weblate is not opening a PR although there are new strings - this is blocking the next release.

**Comment by DavidMStraub** [comment]
@Nick-Hall the commits at Github are correctly displayed at https://hosted.weblate.org/projects/gramps-project/web/#history and also the webhook is activated...

**Comment by Nick-Hall** [comment]
I see PR #407 from Weblate.  There are no pending changes, and everything seems to be working normally.

**Comment by DavidMStraub** [comment]
Right, maybe the Weblate bot was just sleeping late :wink:  Thanks!

**Comment by Nick-Hall** [comment]
For more information, read the [Lazy Commits](https://docs.weblate.org/en/latest/admin/continuous.html#lazy-commits) section in the documentation.  We have [Age of changes to commit](https://docs.weblate.org/en/latest/admin/projects.html#age-of-changes-to-commit) set to 24 hours.

I usually flush pending changes as part of the release process.
