### ISSUE TITLE
Relationship graph syntax error

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-web#412]
Hi @geostag, testing the new relationship chart on my own tree, I am encountering a JS syntax error `Uncaught (in promise) Error: syntax error in line 1347 near '-'` when I navigate to specific people. I am not sure what the root cause is, but I suspect it has something to do with two cousins being married, so two grandparents are identical.

I also noticed (might be related or not) that people can show up twice in such cases, or when they have multiple marriages

![image](https://github.com/gramps-project/gramps-web/assets/10965193/8499c44b-170f-4aeb-8a7d-8be5dbc0d255)

**Comment by geostag** [comment]
Persons showing up more than once is intended, if they are part of more than one family and their partners or children are also part of the graph. This is the situation I tried to [describe](https://github.com/gramps-project/gramps-web/issues/313#issuecomment-1890939561).

The JS syntax error obviously is not. Could you give some more details, e.g. the stacktrace from the browser console?

**Comment by DavidMStraub** [comment]
![image](https://github.com/gramps-project/gramps-web/assets/10965193/2e8b3caf-17f0-41f0-825a-16da2ea45c2a)

**Comment by geostag** [comment]
Seems to be a syntax error in the generated dot string. Could you do me a favour and add  `console.log(dot)` before line 186 in RelationshipChart.js and show the line the error refers to - if this is possible? Currently I have no idea how a '-02' should make it to the generated dot depending on individual data. 

I am assuming, that the `handle` from api data is a save alphanumeric string. If this not the case, I have to rework the code.

**Comment by DavidMStraub** [comment]
Here (trying out locally now) it says "line 2476 near '-02'", line 2476 would be the third line here - not sure if this is the right counting though...

```
      subgraph cluster_p_53ce42d5-02cd-4d82-bbfb-db3449fe038c {
        cluster=true
        color=white
        label="."
        node_p_53ce42d5-02cd-4d82-bbfb-db3449fe038cx53ce42d5-02cd-4d82-bbfb-db3449fe038c [
          class="person_53ce42d5-02cd-4d82-bbfb-db3449fe038c"
          margin=0.25
          shape="none"
          fixedsize=true
          width=2.878787878787879
          height=1.0636363636363635
          label=<->
        ]
      }
```

**Comment by DavidMStraub** [comment]
Actually it's the only subgraph with the string `-02`, so  might be something in there.

**Comment by DavidMStraub** [comment]
I ran this on the command line with `dot` and got

```
Warning: syntax ambiguity - badly delimited number '-02c' in line 2475 of graph.dot splits into two tokens
Error: graph.dot: syntax error in line 2475 near '-02'
```

**Comment by DavidMStraub** [comment]
For some reason it seems handles with hyphens cause problems. And Gramps Web API uses UUIDv4s with hyphens :grimacing:

I suspect quotation marks might be enough to fix it https://stackoverflow.com/questions/14958346/dot-dash-in-name

**Comment by DavidMStraub** [comment]
I'll try that out

**Comment by DavidMStraub** [comment]
That fixed it! Will push directly

**Comment by andre1wall** [comment]
I am experiencing some problems with the correct sorting of the main person's descendants.
maybe i'm the only one experiencing these errors as my family tree is quite large, but it would be good if the descendants were always sorted by year of birth and no distinction was made as to whether the people were married or not, as this should not affect the view.

wrong sorting descendants:
![gramps-web-realationship-praph](https://github.com/gramps-project/gramps-web/assets/36610567/86e197c2-96d1-42e2-a34e-5a5b62a8da05)
![sorting](https://github.com/gramps-project/gramps-web/assets/36610567/984c25de-b37e-4616-9836-89f4045fae88)


a person who has been married twice is reported twice:
![the same person was married twice1](https://github.com/gramps-project/gramps-web/assets/36610567/c922e6e7-fb80-4ec8-a338-e1d4e5f79fad)
![the same person was married twice2](https://github.com/gramps-project/gramps-web/assets/36610567/5ae3831b-6a47-4370-b026-f86c2fe1678f)

thank you for your hard work i really appreciate it.
this view was really missing.
please continue with your great work

**Comment by geostag** [comment]
We are using graphviz, a common software library to render and layout arbitrary graphs. The algorythm tries to minimize the number of crossing edges. This is well accepted as helpful when displaying large directed graphs. But it definetly has the effect, that other sorting crierteria like date of birth are not taken into account. 

Displaying persons which are part of more than one family multiple times is intended as discussed in #313 . It seems to be the best option in these cases.
