### ISSUE TITLE
Error when a link to a MediaObject is added to a notation for a Blog

### ISSUE THREAD

**Issue by Jimbosss** [gramps-project/gramps-web#413]
When I create a Blog post in Gramps by using a Source with a Label blog everything works fine in Grampsweb.
After I created a Link to a Wikipedia page, this also works in Grampsweb.
 ( is it possible to open an external link to a new Tab instead of the excisting one ? )

But after I create a link to a MediaObject (JPG Image) in that same Blogpost, I see nothing when I click on that link.
Looking at the Debug Console in the browser, I see the following error:

Uncaught (in promise) TypeError: e.media_list is undefined		7f4e2c83.js:8394:259

I am using

Gramps 5.2.0
Gramps Web API 2.1.0
Gramps Web Frontend 24.3.1
locale: en
multi-tree: false
task queue: true

**Comment by DavidMStraub** [comment]
Ok this is a bug; can you please check the following pages individually and tell me which ones load (when you reload them with F5) and which ones error:

- the note view of the blog post
- the blog overview page
- the blog post view
- the media view of the linked media object
- the source view of the blog post source

Thanks!

**Comment by Jimbosss** [comment]
http://localhost/ [Fine]  Shows latest blogpost
http://localhost/blog  [Fine]
http://localhost/blog/S0007 [Fine]
http://localhost/source/S0007 [Fine]
http://localhost/note/N0010 [Fine]

http://localhost/media/O0918 [Error]
