### ISSUE TITLE
Setting up HTTPS with Let's Encrypt and Docker Compose = doesn't work

### ISSUE THREAD

**Issue by amashkin** [gramps-project/gramps-web#418]
Original instuction contains docker-compose.yml that doesn't work. 
https://www.grampsweb.org/LetsEncrypt/
It is reproducible on Ubuntu and Debian instances.

Error: 
nginx-proxy         | nginx.1     | nginx: [crit] pread() "/etc/nginx/conf.d/my_proxy.conf" failed (21: Is a directory)

Issue comes from:
- ./nginx_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro

nginx_proxy cannot start since nginx_proxy.conf is a dirrectory where impossible to store nginx_proxy.conf file.

Related posts
https://gramps.discourse.group/t/setup-issues-gramps-web-on-vps-with-ssl/3761/18
https://gramps.discourse.group/t/gramps-web-nginx-configuration-file/3128/7

**Comment by DavidMStraub** [comment]
Hi, looks like a setup issue and is not an issue with the Gramps Web frontend, so I'll close this issue. We can continue diagnosing in the forum where you also posted - that's the right place for now.
