### ISSUE TITLE
Release tag and free text misaligned

### ISSUE THREAD

**Issue by vulcanjedi** [gramps-project/gramps-web#420]
FYI release tag and text is off 
> 
![image](https://github.com/gramps-project/gramps-web/assets/2159292/f4dbdc7b-2e94-4df3-ba8a-2bb4c4de2b3e)
>

**Comment by DavidMStraub** [comment]
Oops 😮 thanks for the heads up. Will release a new tag tonight then.

**Comment by DavidMStraub** [comment]
Ah no, the tag was fine as you wrote, so I just renamed the release. ✔️
