### ISSUE TITLE
Not able to edit images if OpenCV is not installed

### ISSUE THREAD

**Issue by Zegeri** [gramps-project/gramps-web#424]
If OpenCV python bindings are not installed on the server, media objects won't show up in edit mode. In this case, the user can't tag faces. OpenCV is used for face detection, but this feature should not be required.

**Comment by DavidMStraub** [comment]
That's true. Since OpenCV is included in the default docker images, I would consider adding handling for this special case (OpenCV not being present) in the relevant view function(s) low priority, but a contribution would be welcome.
