### ISSUE TITLE
Allow external user authentication via OIDC or SAML

### ISSUE THREAD

**Issue by ManfredSchenk** [gramps-project/gramps-web#449]
Since nowadays security policies require the use of 2FA for personal data it would be nice to have an integration with external auth providers like keycloak or similar services. By having such an integration the gramps-web project would not need to implement all authentication stuff by itself but could use existing well-audited code for security related use-cases.

**Comment by DavidMStraub** [comment]
Hi, we already have two feature requests for additional authentication providers, please feel free to add details to one of those. Note that authentication is handled by Gramps Web API (the backend).
https://github.com/gramps-project/gramps-web-api/issues/355
https://github.com/gramps-project/gramps-web-api/issues/423
