### ISSUE TITLE
Picture for each node in RelationshipsTree

### ISSUE THREAD

**Issue by JulKoroleva** [gramps-project/gramps-web#450]
Each version of the family tree has an image for each person, but in the **relationship tree** there are no images for the persons when displaying genealogical connections, only names/date/etc. Could you please add the corresponding functionality so that people's photos are displayed there too? Thank you so much!

**Comment by geostag** [comment]
The relationship graph was intended to possibly display a very large part of the gramps project. Thus displaying a possible image for each person might lead to heavy load on server side. However, we could limit the number of images displayed to prevent this situation and thus display the images up to this limit, which should give the desired result in any case, when the number persons is low enough.

**Comment by geostag** [comment]
@DavidMStraub thanks for rebasing and fixing the text length issue. This issue solved with #451
