### ISSUE TITLE
Feature Request: Remove OpenCV and LibLLVM from Docker Image

### ISSUE THREAD

**Issue by thickconfusion** [gramps-project/gramps-web#469]
https://github.com/gramps-project/gramps-web/blob/ed86b76984ff0dbb4064aa6b3ad0c566d86d6261/Dockerfile#L1C6-L1C35

Is pulling from https://github.com/gramps-project/gramps-web-api/, which has lines https://github.com/gramps-project/gramps-web-api/blob/c6dbfd4cc78309bb23ea1a0dbb0ed397f84f900e/Dockerfile#L13-L25

These are installing LibOpenCV and LibLLVM. These take a lot of disk space and I suspect should be considered downloadable add-ons instead of part of the base Docker image.

**Comment by DavidMStraub** [comment]
First of all, this is the wrong repository.

Secondly, I respect your opinion but I disagree. The docker image is not part of the Gramps Web API Python package. It is a convenience offering a fully featured ready-to-use environment to those who need it. If you don't need it, it's trivial to create a customized docker file.
