### ISSUE TITLE
Allow renaming repositories

### ISSUE THREAD

**Issue by gustavi** [gramps-project/gramps-web#471]
**Description**

We can edit notes or add tags but repositories can't be renamed.

**How to reproduce**

1. Create a repository
2. Edit it (button bottom right)
3. The name can't be edited

![image](https://github.com/user-attachments/assets/594937f6-b29c-431b-a621-53414f949e9e)

**Additional information**

- Gramps 5.2.2
- Gramps Web API 2.3.1
- Gramps Web Frontend 24.7.0
- Gramps QL 0.3.0
- locale: en
- multi-tree: false
- task queue: false

**Comment by Naeit** [comment]
![Screenshot_2024-07-21-09-31-49-588_com.android.chrome.jpg](https://github.com/user-attachments/assets/14fe1e6c-2bd0-4eb7-851b-cbac23742673)

I would like to add that data of Sources are also not editable. Maybe that could be added to, if it is intended to be editable.

`

Gramps 5.2.2
Gramps Web API 2.3.1
Gramps Web Frontend 24.7.0
Gramps QL 0.3.0
locale: en
multi-tree: true
task queue: true

Gramps Web via grampshub.com

`

**Comment by DavidMStraub** [comment]
That one is tracked in https://github.com/gramps-project/gramps-web/issues/57.

**Comment by gustavi** [comment]
@DavidMStraub it's **really** hard to use. Every time I stop typing for 1s the field is saved and I loose the "input". I have to copy-paste from a text editor to use it.

**Comment by DavidMStraub** [comment]
How come you need more than 1 second? 😄

Which browser do you use?

**Comment by DavidMStraub** [comment]
And please check if you have the same issue when editing task titles

**Comment by gustavi** [comment]
> How come you need more than 1 second? 😄

I often copy from manual notes, PDF or external website. The time it takes to remember a combination of random numbers or a complicated name of a village in France is much greater than the time available to me. :smile: 

> Which browser do you use?

Firefox LTS.

> And please check if you have the same issue when editing task titles

Same issue.

I suggest the following modification: don't trigger the "save" event until the mouse has moved outside the input (or for a very long time, 10s for example). Another option: send periodic saves but keep editing possible until you click elsewhere on the page.

**Comment by DavidMStraub** [comment]
I don't see a need to change the behaviour. It works perfectly fine on my end in FF 128. It uses the contenteditable HTML attribute, so no need to watch mouse behaviour. Could be that this older FF version doesn't handle it properly. Works on Chrome as well.
