### ISSUE TITLE
Gramps XML export fails with 'can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by EvilCartyen** [gramps-project/gramps-web#474]
I imported a family tree-backup from the desktop version to gramps web, and now I've done a bunch of work on it (thanks for the tool!), and would like to back it up but I am met with this error when trying.

![image](https://github.com/user-attachments/assets/3783af68-e986-409e-8551-2d354cb370b0)

I assume I have some weird data somewhere, but I am not sure how to proceed to fix it.

**Comment by DavidMStraub** [comment]
Hi,

that error is already tracked here
https://github.com/gramps-project/gramps-web-api/issues/479
so I will close this one.

But it would be great if you could help investigate.

Can you please go to the list views (people etc.), open the filter, choose GQL and try out the following filter:

`media_list.any = None`

for all of the object types except media and notes? Does it give any results?

Background: There is an object in your database that has a `None` as handle in the media list.

**Comment by EvilCartyen** [comment]
Thanks - no results, though. I restarted the container and tried again, still no result, and also same error when exporting.

My instance is public if you want to investigate :)

**Comment by DavidMStraub** [comment]
:scream: public?

**Comment by EvilCartyen** [comment]
I mean, a public URL but you need an account still, of course...

**Comment by EvilCartyen** [comment]
Anyway, I would appreciate suggestions on how to proceed, I an uneasy having no backups with all the work I have been doing :)

**Comment by DavidMStraub** [comment]
Yep understood. So you need to find out which of your objects has a "None" in the `media_list`. Would you feel confident enough to manually query the API via command line?

https://www.grampsweb.org/dev-backend/queries/

You need to fetch the `/api/people`, etc. for the other object types, endpoints and check where there is a `None` in the `media_list`.

You could also employ my poorly known library https://github.com/DavidMStraub/gramps-web-api-client.

**Comment by EvilCartyen** [comment]
I finally got around to learning how to do this - sorry for being slow :) Anyway, I queries the API and retrieved:

* citations
* events
* families
* media
* notes
* people
* places
* repositories
* sources

None of them (heh) have 'None' written anywhere in the json, but maybe I am searching for the wrong thing. What exactly am I looking for? :)

**Comment by DavidMStraub** [comment]
Python `None` corresponds to `null` in JS, perhaps that?

**Comment by EvilCartyen** [comment]
All dates have a "format": null value - what exactly am I looking for?

```
"media_list": [
 null
],
```
?

**Comment by odiouschris** [comment]
Accepting the demonstrated (above) problems with:
a) proposed GQL queries (above),
b) "fragile" Gramps Web (GW) markup (above), and,
c) lack of a timely response ([DavidMStraub] [on Sep 20, 2024](https://github.com/gramps-project/gramps-web/issues/474#issuecomment-2363207961)),

I can propose a workaround (which took me ~15 hours to puzzle out), and might not work for other affected users, and which requires approximately ~1.5 hours per problem (after correcting the initial error in the GW markup, you may find subsequent errors).

Given this information, I'm happy to share what I've learned, however I would prefer the impetus to fall on @DavidMStraub to fix "our bug" (perhaps in 2026).

**Comment by DavidMStraub** [comment]
@odiouschris stay respectful. I will hide comments like that (and don't start arguing about it).

**Comment by odiouschris** [comment]
Apology: I have been informed by A Community Leader (Enforcing his/her/their Responsibilities) per CODE_OF_CONDUCT.md, that my response was 

<img width="194" height="50" alt="Image" src="https://github.com/user-attachments/assets/b89df23c-8b05-4be3-8ce9-88370733f573" />

> ## Enforcement Responsibilities
> 
> Community leaders are responsible for clarifying and enforcing our standards of
> acceptable behavior and will take appropriate and fair corrective action in
> response to any behavior that they deem inappropriate, threatening, offensive,
> or harmful.
> 
> Community leaders have the right and responsibility to remove, edit, or reject
> comments, commits, code, wiki edits, issues, and other contributions that are
> not aligned to this Code of Conduct, and will communicate reasons for moderation
> decisions when appropriate.

My bad. I will continue to review the CODE_OF_CONDUCT.md in order not to offend the Community Leader(s) or negatively impact the Community.
