### ISSUE TITLE
Place type cannot be edited if non-existent

### ISSUE THREAD

**Issue by m-breitbach** [gramps-project/gramps-web#481]
It seems that the place type cannot be edited if non-existent (i.e. if the backend delivers an empty string). Or do I have trouble seeing the appropriate button? Tested on Firefox and Chrome.

<img width="343" alt="image" src="https://github.com/user-attachments/assets/eee2a331-2524-4b22-905b-dd51a26d58df">

**Comment by m-breitbach** [comment]
Another problems with place types: The dropdown menu is truncated. Entries above "Region" thus cannot be selected.
<img width="838" alt="image" src="https://github.com/user-attachments/assets/1405f54e-8c83-4eed-bd19-b6779ec10e87">

**Comment by DavidMStraub** [comment]
Thanks, the first one is easy to fix, let's cover the second one in #470.

**Comment by m-breitbach** [comment]
Hats off! The speed of your support is something I usually don't even experience with enterprise-level support.
