### ISSUE TITLE
Gramps web confirmation emails not received

### ISSUE THREAD

**Issue by Userprogen** [gramps-project/gramps-web#488]
I navigated to the Gramps Web demonstration site from the web tab on the Gramps Project site and was prompted to register for an account. I did so and a verification email was supposed to have been sent to my email. I did not receive it and no, it is not in spam. I tried to log in and retrieve my account using "forgot password" but it says wrong user name.  I see no user support options so created yet another account just to access this forum and am posting here.  If someone reads this and corrects the issue, it would be appreciated, although I am thinking it is unwise for me to use software or a site that can't even process a new account. Thank you.

**Comment by DavidMStraub** [comment]
Hi, registration doesn't work for the demo server. You need to use one of the existing accounts, e.g. `owner`, password `owner`.
