### ISSUE TITLE
Adopted sister is displayed as step sister

### ISSUE THREAD

**Issue by angiioh** [gramps-project/gramps-web#496]
Hi there! I just imported a gedcom file into a new family tree via Gramps Web. While reviewing the tree, I noticed my sister is being listed as my step sister. When I view her events, it shows that it thinks our father is her step-father. 

I went into the Family unit with our mother and father and removed their children (my sister and me) and then readded them and made sure that I was selecting 'adopted' for my sister. After saving though, it's still listing her as a step sibling with a step father. 

Any advice? Or is this a bug?

Thanks for your time!

**Comment by DavidMStraub** [comment]
Hi,

Gedcom import is handled by Gramps core, so if you think it is a bug please report it at https://gramps-project.org/bugs/ or ask for advide in the forum, https://gramps.discourse.group/.

Please make sure to add the relevant snippet from your `GEDCOM` to see exactly what the source data was. It might also be worth reviewing the Wiki page https://www.gramps-project.org/wiki/index.php/Gramps_and_GEDCOM which discusses different treatment in Gedcom vs Gramps when it comes to adoption.

Closing here as it's not a Gramps Web issue.
