### ISSUE TITLE
Child does not show up in descendant & hourglass view if no father is registered

### ISSUE THREAD

**Issue by EvilCartyen** [gramps-project/gramps-web#511]
My sister has a kid with an anonymous donor and no partner. 
![image](https://github.com/user-attachments/assets/616dbefc-99ae-46a6-87b3-4bf8744d5f02)
Kid shows up alright in the relationship graph...
![image](https://github.com/user-attachments/assets/9665f3ea-5bd2-47ea-8671-dae33046ae49)
...but not in hourglass or descendant tree view:
![image](https://github.com/user-attachments/assets/ca4c6cfd-4dfa-4507-90f3-8d984d0204d3)

Registered on:

Gramps 5.2.2
Gramps Web API 2.4.2
Gramps Web Frontend 24.8.0

(And earlier versions)

**Comment by DavidMStraub** [comment]
I'm not able to reproduce that in my tree for ancestors with unkown fathers. Is this the case for all single-parent families in your tree?

**Comment by EvilCartyen** [comment]
Actually no, I just found another person with no partner registered and her children show up fine. I wonder what the issue is then.

They seem to be created and registered in the same manner.

**Comment by EvilCartyen** [comment]
I just tested with a new child, shows up fine. So I don't know what's up with the existing bond. Closing this.

**Comment by DavidMStraub** [comment]
Perhaps it something was wrong with the child ref type, although I'm not sure what could cause this.
