### ISSUE TITLE
Getting the ports right with docker compose, with Caddy as reverse proxy?

### ISSUE THREAD

**Issue by amca01** [gramps-project/gramps-web#525]
**Note:** I've asked this on the Gramps forum, but got no reply.  I would have hoped that somebody, somewhere may be using Gramps-web with Caddy, but if they are, they seem to have better things to do than answer my idiot questions!

**Short version:** What ports should I set in my docker compose file, given that 80 is already allocated, and that I want to use Caddy as a reverse proxy?

**Longer version:** I'm a bit confused about what ports to use, or to set, with Gramps-web.  According to the standard [docker compose file](https://raw.githubusercontent.com/gramps-project/gramps-web-docs/main/examples/docker-compose-base/docker-compose.yml) linked on the "deploy with docker" section of the installation docs, the ports for the outward facing Gramps-web container are "80:5000".

But according to the [example on this github repo](https://github.com/gramps-project/gramps-web/blob/main/docker-compose.yml), for use with nginx, the ports are given as "5555:80"

I'm using Caddy as my reverse proxy and for managing TLS certificates from LetsEncrypt.  I can get Gramps-web up and running if I set the ports to "8001:5000"  (I can't use 80 as that's already used by Caddy), and set the Caddyfile port to 5000.  

This means I can start Gramps-web, and get the page for creating a new user.  But then clicking on "Submit" produces "Error: Error 500".

So something is not right, and I'm assuming that the main culprit is the ports.

Any advice would be welcome!  Many thanks.

**Comment by DavidMStraub** [comment]
Hi,

the Gramps forum ist the right place to ask, the issue tracker for the Gramps Web frontend is not.

I've seen your forum post but have nothing to add as I have no experience with Caddy.

Please refrain from double posting in the future. Thank you.

Reference: https://gramps.discourse.group/t/installing-gramps-web-with-docker-compose-and-caddy-as-reverse-proxy/6354
