### ISSUE TITLE
Problems with Relationship Chart

### ISSUE THREAD

**Issue by WWerkel** [gramps-project/gramps-web#533]
I have made an installation of Gramps-Web with the current installation files, but unfortunately the relationship chart does not work. No graph is displayed regardless of which settings I choose in `Degree of Separation` or `Max. Number of Images` I choose.
Does anyone have any advice?

**Comment by DavidMStraub** [comment]
It works for me. Please share the version info, settings, browser version, ...

**Comment by WWerkel** [comment]
We used the latest version: 
Gramps 5.2.3
Gramps Web API 2.5.2
Gramps Web Frontend 24.10.0
Gramps QL 0.3.0
Sifts 1.0.0
locale: en
multi-tree: false
task queue: true
OCR: true
chat: false

OS: Windows 10 Pro Version 22H2
Browser: 
1. Google Chrome Version 131.0.6778.86
2. Firefox Version 132.0.2

**Comment by DavidMStraub** [comment]
You can check the browser console (F12) to see if any errors are generated.

**Comment by DavidMStraub** [comment]
Please provide details on your setup (docker compose file, etc.).

**Comment by WWerkel** [comment]
Gramps Web is behind an Apache as a reverse proxy.

**Our docker compose file:**

services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "127.0.0.1:5000:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
      GUNICORN_NUM_WORKERS: 2
      GRAMPSWEB_EMAIL_HOST: “172.18.0.1”
      GRAMPSWEB_EMAIL_PORT: 25
      GRAMPSWEB_EMAIL_USE_TLS: 0
      GRAMPSWEB_FROM_EMAIL: “XXXXXXXXXXXXXXXXXXXXX”
      GRAMPSWEB_BASE_URL: “https://XXXXXXXXXXXXX.net/”
    depends_on:
      - grampsweb_redis
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - /home/gramps/gramps_media:/app/media  # persist media files
        #      - /home/gramps/config.cfg:/app/config/config.cfg
      - gramps_tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO --concurrency=2

  grampsweb_redis:
    image: docker.io/library/redis:7.2.4-alpine
    container_name: grampsweb_redis
    restart: always

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
  gramps_tmp:

**Server configuration:**
<IfModule mod_ssl.c>
	<VirtualHost _default_:443>
		Protocols h2 http/1.1
		# Add six earth month HSTS header for all users...
		Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
		ServerAdmin XXXXXX.net
		ServerName XXXXXX.net

		SSLProxyEngine on
		ProxyRequests off
		ProxyPreserveHost off
		# tested with on without changes
		#ProxyRequests on
		#ProxyPreserveHost on

		ProxyPass        / http://localhost:5000/ connectiontimeout=5 timeout=300
		<Location />
		    ProxyPassReverse /
		</Location>

		<Proxy *>
		    Require all granted
	       </Proxy>

		# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
		# error, crit, alert, emerg.
		# It is also possible to configure the loglevel for particular
		# modules, e.g.
		#LogLevel info ssl:debug
		Logformat "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" ssl_combined

		ErrorLog ${APACHE_LOG_DIR}/ssl_genealogie.error.log
		CustomLog ${APACHE_LOG_DIR}/ssl_genealogie.access.log ssl_combined

		# For most configuration files from conf-available/, which are
		# enabled or disabled at a global level, it is possible to
		# include a line for only one particular virtual host. For example the
		# following line enables the CGI configuration for this host only
		# after it has been globally disabled with "a2disconf".
		#Include conf-available/serve-cgi-bin.conf

		#   SSL Engine Switch:
		#   Enable/Disable SSL for this virtual host.
		SSLEngine on

		#   A self-signed (snakeoil) certificate can be created by installing
		#   the ssl-cert package. See
		#   /usr/share/doc/apache2/README.Debian.gz for more info.
		#   If both key and certificate are stored in the same file, only the
		#   SSLCertificateFile directive is needed.
		#SSLCertificateFile	/etc/letsencrypt/live/xxxxx.net-0002/fullchain.pem
		#SSLCertificateKeyFile /etc/letsencrypt/live/xxxxx.net-0002/privkey.pem
		SSLCertificateFile	/var/lib/dehydrated/certs/xxxxxx.net/fullchain.pem
		SSLCertificateKeyFile /var/lib/dehydrated/certs/xxxxxxx.net/privkey.pem

		#   Server Certificate Chain:
		#   Point SSLCertificateChainFile at a file containing the
		#   concatenation of PEM encoded CA certificates which form the
		#   certificate chain for the server certificate. Alternatively
		#   the referenced file can be the same as SSLCertificateFile
		#   when the CA certificates are directly appended to the server
		#   certificate for convinience.
		#SSLCertificateChainFile /etc/apache2/ssl.crt/server-ca.crt
		#SSLCertificateChainFile /etc/letsencrypt/live/xxxxxxx.net/chain.pem

		#   Certificate Authority (CA):
		#   Set the CA certificate verification path where to find CA
		#   certificates for client authentication or alternatively one
		#   huge file containing all of them (file must be PEM encoded)
		#   Note: Inside SSLCACertificatePath you need hash symlinks
		#		 to point to the certificate files. Use the provided
		#		 Makefile to update the hash symlinks after changes.
		#SSLCACertificatePath /etc/ssl/certs/
		#SSLCACertificateFile /etc/apache2/ssl.crt/ca-bundle.crt

		#   Certificate Revocation Lists (CRL):
		#   Set the CA revocation path where to find CA CRLs for client
		#   authentication or alternatively one huge file containing all
		#   of them (file must be PEM encoded)
		#   Note: Inside SSLCARevocationPath you need hash symlinks
		#		 to point to the certificate files. Use the provided
		#		 Makefile to update the hash symlinks after changes.
		#SSLCARevocationPath /etc/apache2/ssl.crl/
		#SSLCARevocationFile /etc/apache2/ssl.crl/ca-bundle.crl

		#   Client Authentication (Type):
		#   Client certificate verification type and depth.  Types are
		#   none, optional, require and optional_no_ca.  Depth is a
		#   number which specifies how deeply to verify the certificate
		#   issuer chain before deciding the certificate is not valid.
		SSLVerifyClient none
		#SSLVerifyClient require
		#SSLVerifyDepth  10

		#   SSL Engine Options:
		#   Set various options for the SSL engine.
		#   o FakeBasicAuth:
		#	 Translate the client X.509 into a Basic Authorisation.  This means that
		#	 the standard Auth/DBMAuth methods can be used for access control.  The
		#	 user name is the `one line' version of the client's X.509 certificate.
		#	 Note that no password is obtained from the user. Every entry in the user
		#	 file needs this password: `xxxxxxxx'.
		#   o ExportCertData:
		#	 This exports two additional environment variables: SSL_CLIENT_CERT and
		#	 SSL_SERVER_CERT. These contain the PEM-encoded certificates of the
		#	 server (always existing) and the client (only existing when client
		#	 authentication is used). This can be used to import the certificates
		#	 into CGI scripts.
		#   o StdEnvVars:
		#	 This exports the standard SSL/TLS related `SSL_*' environment variables.
		#	 Per default this exportation is switched off for performance reasons,
		#	 because the extraction step is an expensive operation and is usually
		#	 useless for serving static content. So one usually enables the
		#	 exportation for CGI and SSI requests only.
		#   o OptRenegotiate:
		#	 This enables optimized SSL connection renegotiation handling when SSL
		#	 directives are used in per-directory context.
		#SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire
		SSLOpenSSLConfCmd ECDHParameters secp521r1
		#SSLOpenSSLConfCmd Curves prime256v1:secp521r1:secp384r1
		SSLOpenSSLConfCmd Curves X25519:secp521r1:secp384r1:prime256v1
		SSLOpenSSLConfCmd DHParameters "/etc/apache2/ffdhe4096"
		<FilesMatch "\.(cgi|shtml|phtml|php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>
		<Directory /usr/lib/cgi-bin>
				SSLOptions +StdEnvVars
		</Directory>

		#   SSL Protocol Adjustments:
		#   The safe and default but still SSL/TLS standard compliant shutdown
		#   approach is that mod_ssl sends the close notify alert but doesn't wait for
		#   the close notify alert from client. When you need a different shutdown
		#   approach you can use one of the following variables:
		#   o ssl-unclean-shutdown:
		#	 This forces an unclean shutdown when the connection is closed, i.e. no
		#	 SSL close notify alert is send or allowed to received.  This violates
		#	 the SSL/TLS standard but is needed for some brain-dead browsers. Use
		#	 this when you receive I/O errors because of the standard approach where
		#	 mod_ssl sends the close notify alert.
		#   o ssl-accurate-shutdown:
		#	 This forces an accurate shutdown when the connection is closed, i.e. a
		#	 SSL close notify alert is send and mod_ssl waits for the close notify
		#	 alert of the client. This is 100% SSL/TLS standard compliant, but in
		#	 practice often causes hanging connections with brain-dead browsers. Use
		#	 this only for browsers where you know that their SSL implementation
		#	 works correctly.
		#   Notice: Most problems of broken clients are also related to the HTTP
		#   keep-alive facility, so you usually additionally want to disable
		#   keep-alive for those clients, too. Use variable "nokeepalive" for this.
		#   Similarly, one has to force some clients to use HTTP/1.0 to workaround
		#   their broken HTTP/1.1 implementation. Use variables "downgrade-1.0" and
		#   "force-response-1.0" for this.
		BrowserMatch "MSIE [2-6]" \
				nokeepalive ssl-unclean-shutdown \
				downgrade-1.0 force-response-1.0
		# MSIE 7 and newer should be able to use keepalive
		BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

	</VirtualHost>
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

**Comment by DavidMStraub** [comment]
Our documentation does not mention Apache as reverse proxy. That doesn't mean you can't use it, but we cannot provide support for debugging issues like the CSP one you encountered. Feel free to open a discussion or forum post to get support on this non-standard setup. I am closing this issue because it doesn't look like a bug in Gramps Web.
